language: php

sudo: required

jobs:
  fast_finish: true
  include:
    - php: 7.2
      env: SWOOLE_VERSION=4.5.11 HYPERF_VERSION=1.0.* PHPUNIT_VERSION=^7.0.0
    - php: 7.2
      env: SWOOLE_VERSION=4.5.11 HYPERF_VERSION=1.1.* PHPUNIT_VERSION=^7.0.0
    - php: 7.2
      env: SWOOLE_VERSION=4.5.11 HYPERF_VERSION=2.0.* PHPUNIT_VERSION=^7.0.0
    - php: 7.3
      env: SWOOLE_VERSION=4.6.7 HYPERF_VERSION=2.1.* PHPUNIT_VERSION=^9.4
    - php: 7.4
      env: SWOOLE_VERSION=4.7.0 HYPERF_VERSION=2.2.* PHPUNIT_VERSION=^9.5
    - php: 8.0
      env: SWOOLE_VERSION=4.7.0 HYPERF_VERSION=2.2.* PHPUNIT_VERSION=^9.5

before_install:
  - travis_retry composer self-update
  - composer require "hyperf/di:${HYPERF_VERSION}" --no-update --prefer-dist
  - composer require "hyperf/http-server:${HYPERF_VERSION}" --no-update --prefer-dist
  - composer require "hyperf/config:${HYPERF_VERSION}" --no-update --prefer-dist --dev
  - composer require "hyperf/testing:${HYPERF_VERSION}" --no-update --prefer-dist --dev
  - composer require "hyperf/validation:${HYPERF_VERSION}" --no-update --prefer-dist --dev

install:
  - cd $TRAVIS_BUILD_DIR
  - bash .travis/swoole.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis/ci.ini
  - cp phpunit.xml.dist phpunit.xml
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - composer test
